# -*- coding: utf-8 -*-
"""YoloTraining_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16tXEP0ZXMJYw7L1Chq7iBff2M_j-KWBF
"""

!pip install ultralytics

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo checks

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="gWg6CT0tm7WHxZT2GoDw")
project = rf.workspace("digital-image-processing-k3cbl").project("plastic-detection-dataset")
dataset = project.version(1).download("yolov8")

!yolo task=detect mode=train model=yolov8n.pt data={dataset.location}/data.yaml epochs=30 imgsz=640

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train/results.png', width=600)

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt source={dataset.location}/test/images imgsz=640

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg'):
  display(Image(filename=image_path, height=600))
  print("\n")